/**
 * Dashboard routing contract.
 *
 * Each segment maps to an anchor rendered by `authorized-dashboard.tsx` and to
 * a static route generated by `app/(workspace)/[section]/page.tsx`, which keeps
 * the shell compatible with `output: 'export'`.
 */
export const DASHBOARD_SEGMENTS = [
  'overview',
  'sprint',
  'intelligence',
  'knowledge',
  'tools',
  'reports',
  'portfolio',
  'finops',
  'contracts',
  'tasks',
  'vault',
] as const

export type DashboardSegment = (typeof DASHBOARD_SEGMENTS)[number]

export function isDashboardSegment(value: string): value is DashboardSegment {
  return (DASHBOARD_SEGMENTS as readonly string[]).includes(value)
}

export function isDashboardPath(pathname: string): boolean {
  if (pathname === '/') return true
  return DASHBOARD_SEGMENTS.some(
    (segment) => pathname === `/${segment}` || pathname.startsWith(`/${segment}/`),
  )
}

export function isLoginPath(pathname: string): boolean {
  return pathname === '/login' || pathname.startsWith('/login/')
}
